<?php

namespace App\Http\Controllers;

use App\Models\Donor;
use App\Models\GetDonor;
use Illuminate\Http\Request;
use PhpParser\Node\Stmt\Do_;

class LaporanController extends Controller
{
    public function bulanan()
    {


        return view('dashboard.bulanan.index', [
            // 18tahun
            'jumlahdonasi1' => Donor::where('umur', '<', 18)->where('bulan', date('m Y'))->count(),
            'sukarelabaruQ' => Donor::where('umur', '<', 18)->where('tempatdonor', 'PMI')->where('macamdonor', 'sukarela (baru)')->where('bulan', date('m Y'))->count(),
            'sukarelaulangQ' => Donor::where('umur', '<', 18)->where('tempatdonor', 'PMI')->where('macamdonor', 'sukarela (ulang)')->where('bulan', date('m Y'))->count(),
            'penggantiQ' => Donor::where('umur', '<', 18)->where('tempatdonor', 'PMI')->where('macamdonor', 'pengganti')->where('bulan', date('m Y'))->count(),
            'bayaranQ' => Donor::where('umur', '<', 18)->where('tempatdonor', 'PMI')->where('macamdonor', 'bayaran')->where('bulan', date('m Y'))->count(),
            'mobileunitbaruQ' => Donor::where('umur', '<', 18)->where('tempatdonor', 'Mobile unit')->where('bulan', date('m Y'))->count(),
            'mobileunitulangQ' => Donor::where('umur', '<', 18)->where('tempatdonor', 'Mobile unit')->where('bulan', date('m Y'))->count(),
            'laki2Q' => Donor::where('umur', '<', 18)->where('jeniskelamin', 'laki-laki')->where('bulan', date('m Y'))->count(),
            'perempuanQ' => Donor::where('umur', '<', 18)->where('jeniskelamin', 'perempuan')->where('bulan', date('m Y'))->count(),
            'rhesusO1Q' => Donor::where('umur', '<', 18)->where('rhesus', '+')->where('golongandarah', 'O')->where('bulan', date('m Y'))->count(),
            'rhesusO2Q' => Donor::where('umur', '<', 18)->where('rhesus', '-')->where('golongandarah', 'O')->where('bulan', date('m Y'))->count(),
            'rhesusA1Q' => Donor::where('umur', '<', 18)->where('rhesus', '+')->where('golongandarah', 'A')->where('bulan', date('m Y'))->count(),
            'rhesusA2Q' => Donor::where('umur', '<', 18)->where('rhesus', '-')->where('golongandarah', 'A')->where('bulan', date('m Y'))->count(),
            'rhesusB1Q' => Donor::where('umur', '<', 18)->where('rhesus', '+')->where('golongandarah', 'B')->where('bulan', date('m Y'))->count(),
            'rhesusB2Q' => Donor::where('umur', '<', 18)->where('rhesus', '-')->where('golongandarah', 'B')->where('bulan', date('m Y'))->count(),
            'rhesusAB1Q' => Donor::where('umur', '<', 18)->where('rhesus', '+')->where('golongandarah', 'AB')->where('bulan', date('m Y'))->count(),
            'rhesusAB2Q' => Donor::where('umur', '<', 18)->where('rhesus', '-')->where('golongandarah', 'AB')->where('bulan', date('m Y'))->count(),
            // 18-24 tahun
            'jumlahdonasi2' => Donor::where('umur', '<', 25)->where('umur', '>', 17)->where('bulan', date('m Y'))->count(),
            'sukarelabaru' => Donor::where('umur', '<', 25)->where('tempatdonor', 'PMI')->where('umur', '>', 17)->where('macamdonor', 'sukarela (baru)')->where('bulan', date('m Y'))->count(),
            'sukarelaulang' => Donor::where('umur', '<', 25)->where('tempatdonor', 'PMI')->where('umur', '>', 17)->where('macamdonor', 'sukarela (ulang)')->where('bulan', date('m Y'))->count(),
            'pengganti' => Donor::where('umur', '<', 25)->where('tempatdonor', 'PMI')->where('umur', '>', 17)->where('macamdonor', 'pengganti')->where('bulan', date('m Y'))->count(),
            'bayaran' => Donor::where('umur', '<', 25)->where('tempatdonor', 'PMI')->where('umur', '>', 17)->where('macamdonor', 'bayaran')->where('bulan', date('m Y'))->count(),
            'mobileunitbaru' => Donor::where('umur', '<', 25)->where('umur', '>', 17)->where('tempatdonor', 'Mobile unit')->where('bulan', date('m Y'))->count(),
            'mobileunitulang' => Donor::where('umur', '<', 25)->where('umur', '>', 17)->where('tempatdonor', 'Mobile unit')->where('bulan', date('m Y'))->count(),
            'laki2' => Donor::where('umur', '<', 25)->where('umur', '>', 17)->where('jeniskelamin', 'laki-laki')->where('bulan', date('m Y'))->count(),
            'perempuan' => Donor::where('umur', '<', 25)->where('umur', '>', 17)->where('jeniskelamin', 'perempuan')->where('bulan', date('m Y'))->count(),
            'rhesusO1' => Donor::where('umur', '<', 25)->where('umur', '>', 17)->where('rhesus', '+')->where('golongandarah', 'O')->where('bulan', date('m Y'))->count(),
            'rhesusO2' => Donor::where('umur', '<', 25)->where('umur', '>', 17)->where('rhesus', '-')->where('golongandarah', 'O')->where('bulan', date('m Y'))->count(),
            'rhesusA1' => Donor::where('umur', '<', 25)->where('umur', '>', 17)->where('rhesus', '+')->where('golongandarah', 'A')->where('bulan', date('m Y'))->count(),
            'rhesusA2' => Donor::where('umur', '<', 25)->where('umur', '>', 17)->where('rhesus', '-')->where('golongandarah', 'A')->where('bulan', date('m Y'))->count(),
            'rhesusB1' => Donor::where('umur', '<', 25)->where('umur', '>', 17)->where('rhesus', '+')->where('golongandarah', 'B')->where('bulan', date('m Y'))->count(),
            'rhesusB2' => Donor::where('umur', '<', 25)->where('umur', '>', 17)->where('rhesus', '-')->where('golongandarah', 'B')->where('bulan', date('m Y'))->count(),
            'rhesusAB1' => Donor::where('umur', '<', 25)->where('umur', '>', 17)->where('rhesus', '+')->where('golongandarah', 'AB')->where('bulan', date('m Y'))->count(),
            'rhesusAB2' => Donor::where('umur', '<', 25)->where('umur', '>', 17)->where('rhesus', '-')->where('golongandarah', 'AB')->where('bulan', date('m Y'))->count(),

            // 25 - 44
            'jumlahdonasi3' => Donor::where('umur', '<', 45)->where('umur', '>', 24)->where('bulan', date('m Y'))->count(),
            'sukarelabaruW' => Donor::where('umur', '<', 45)->where('tempatdonor', 'PMI')->where('umur', '>', 24)->where('macamdonor', 'sukarela (baru)')->where('bulan', date('m Y'))->count(),
            'sukarelaulangW' => Donor::where('umur', '<', 45)->where('tempatdonor', 'PMI')->where('umur', '>', 24)->where('macamdonor', 'sukarela (ulang)')->where('bulan', date('m Y'))->count(),
            'penggantiW' => Donor::where('umur', '<', 45)->where('tempatdonor', 'PMI')->where('umur', '>', 24)->where('macamdonor', 'pengganti')->where('bulan', date('m Y'))->count(),
            'bayaranW' => Donor::where('umur', '<', 45)->where('tempatdonor', 'PMI')->where('umur', '>', 24)->where('macamdonor', 'bayaran')->where('bulan', date('m Y'))->count(),
            'mobileunitbaruW' => Donor::where('umur', '<', 45)->where('umur', '>', 24)->where('tempatdonor', 'Mobile unit')->where('bulan', date('m Y'))->count(),
            'mobileunitulangW' => Donor::where('umur', '<', 45)->where('umur', '>', 24)->where('tempatdonor', 'Mobile unit')->where('bulan', date('m Y'))->count(),
            'laki2W' => Donor::where('umur', '<', 45)->where('umur', '>', 24)->where('jeniskelamin', 'laki-laki')->where('bulan', date('m Y'))->count(),
            'perempuanW' => Donor::where('umur', '<', 45)->where('umur', '>', 24)->where('jeniskelamin', 'perempuan')->where('bulan', date('m Y'))->count(),
            'rhesusO1W' => Donor::where('umur', '<', 45)->where('umur', '>', 24)->where('rhesus', '+')->where('golongandarah', 'O')->where('bulan', date('m Y'))->count(),
            'rhesusO2W' => Donor::where('umur', '<', 45)->where('umur', '>', 24)->where('rhesus', '-')->where('golongandarah', 'O')->where('bulan', date('m Y'))->count(),
            'rhesusA1W' => Donor::where('umur', '<', 45)->where('umur', '>', 24)->where('rhesus', '+')->where('golongandarah', 'A')->where('bulan', date('m Y'))->count(),
            'rhesusA2W' => Donor::where('umur', '<', 45)->where('umur', '>', 24)->where('rhesus', '-')->where('golongandarah', 'A')->where('bulan', date('m Y'))->count(),
            'rhesusB1W' => Donor::where('umur', '<', 45)->where('umur', '>', 24)->where('rhesus', '+')->where('golongandarah', 'B')->where('bulan', date('m Y'))->count(),
            'rhesusB2W' => Donor::where('umur', '<', 45)->where('umur', '>', 24)->where('rhesus', '-')->where('golongandarah', 'B')->where('bulan', date('m Y'))->count(),
            'rhesusAB1W' => Donor::where('umur', '<', 45)->where('umur', '>', 24)->where('rhesus', '+')->where('golongandarah', 'AB')->where('bulan', date('m Y'))->count(),
            'rhesusAB2W' => Donor::where('umur', '<', 45)->where('umur', '>', 24)->where('rhesus', '-')->where('golongandarah', 'AB')->where('bulan', date('m Y'))->count(),

            // 45 tahun - 60 tahun
            'jumlahdonasi4' => Donor::where('umur', '<', 60)->where('umur', '>', 44)->where('bulan', date('m Y'))->count(),
            'sukarelabaruE' => Donor::where('umur', '<', 60)->where('tempatdonor', 'PMI')->where('umur', '>', 44)->where('macamdonor', 'sukarela (baru)')->where('bulan', date('m Y'))->count(),
            'sukarelaulangE' => Donor::where('umur', '<', 60)->where('tempatdonor', 'PMI')->where('umur', '>', 44)->where('macamdonor', 'sukarela (ulang)')->where('bulan', date('m Y'))->count(),
            'penggantiE' => Donor::where('umur', '<', 60)->where('tempatdonor', 'PMI')->where('umur', '>', 44)->where('macamdonor', 'pengganti')->where('bulan', date('m Y'))->count(),
            'bayaranE' => Donor::where('umur', '<', 60)->where('tempatdonor', 'PMI')->where('umur', '>', 44)->where('macamdonor', 'bayaran')->where('bulan', date('m Y'))->count(),
            'mobileunitbaruE' => Donor::where('umur', '<', 60)->where('umur', '>', 44)->where('tempatdonor', 'Mobile unit')->where('bulan', date('m Y'))->count(),
            'mobileunitulangE' => Donor::where('umur', '<', 60)->where('umur', '>', 44)->where('tempatdonor', 'Mobile unit')->where('bulan', date('m Y'))->count(),
            'laki2E' => Donor::where('umur', '<', 60)->where('umur', '>', 44)->where('jeniskelamin', 'laki-laki')->where('bulan', date('m Y'))->count(),
            'perempuanE' => Donor::where('umur', '<', 60)->where('umur', '>', 44)->where('jeniskelamin', 'perempuan')->where('bulan', date('m Y'))->count(),
            'rhesusO1E' => Donor::where('umur', '<', 60)->where('umur', '>', 44)->where('rhesus', '+')->where('golongandarah', 'O')->where('bulan', date('m Y'))->count(),
            'rhesusO2E' => Donor::where('umur', '<', 60)->where('umur', '>', 44)->where('rhesus', '-')->where('golongandarah', 'O')->where('bulan', date('m Y'))->count(),
            'rhesusA1E' => Donor::where('umur', '<', 60)->where('umur', '>', 44)->where('rhesus', '+')->where('golongandarah', 'A')->where('bulan', date('m Y'))->count(),
            'rhesusA2E' => Donor::where('umur', '<', 60)->where('umur', '>', 44)->where('rhesus', '-')->where('golongandarah', 'A')->where('bulan', date('m Y'))->count(),
            'rhesusB1E' => Donor::where('umur', '<', 60)->where('umur', '>', 44)->where('rhesus', '+')->where('golongandarah', 'B')->where('bulan', date('m Y'))->count(),
            'rhesusB2E' => Donor::where('umur', '<', 60)->where('umur', '>', 44)->where('rhesus', '-')->where('golongandarah', 'B')->where('bulan', date('m Y'))->count(),
            'rhesusAB1E' => Donor::where('umur', '<', 60)->where('umur', '>', 44)->where('rhesus', '+')->where('golongandarah', 'AB')->where('bulan', date('m Y'))->count(),
            'rhesusAB2E' => Donor::where('umur', '<', 60)->where('umur', '>', 44)->where('rhesus', '-')->where('golongandarah', 'AB')->where('bulan', date('m Y'))->count(),
            // 60 tahun keatas

            'jumlahdonasi5' => Donor::where('umur', '>', 59)->where('bulan', date('m Y'))->count(),
            'sukarelabaruR' => Donor::where('umur', '>', 59)->where('tempatdonor', 'PMI')->where('macamdonor', 'sukarela (baru)')->where('bulan', date('m Y'))->count(),
            'sukarelaulangR' => Donor::where('umur', '>', 59)->where('tempatdonor', 'PMI')->where('macamdonor', 'sukarela (ulang)')->where('bulan', date('m Y'))->count(),
            'penggantiR' => Donor::where('umur', '>', 59)->where('tempatdonor', 'PMI')->where('macamdonor', 'pengganti')->where('bulan', date('m Y'))->count(),
            'bayaranR' => Donor::where('umur', '>', 59)->where('tempatdonor', 'PMI')->where('macamdonor', 'bayaran')->where('bulan', date('m Y'))->count(),
            'mobileunitbaruR' => Donor::where('umur', '>', 59)->where('tempatdonor', 'Mobile unit')->where('bulan', date('m Y'))->count(),
            'mobileunitulangR' => Donor::where('umur', '>', 59)->where('tempatdonor', 'Mobile unit')->where('bulan', date('m Y'))->count(),
            'laki2R' => Donor::where('umur', '>', 59)->where('jeniskelamin', 'laki-laki')->where('bulan', date('m Y'))->count(),
            'perempuanR' => Donor::where('umur', '>', 59)->where('jeniskelamin', 'perempuan')->where('bulan', date('m Y'))->count(),
            'rhesusO1R' => Donor::where('umur', '>', 59)->where('rhesus', '+')->where('golongandarah', 'O')->where('bulan', date('m Y'))->count(),
            'rhesusO2R' => Donor::where('umur', '>', 59)->where('rhesus', '-')->where('golongandarah', 'O')->where('bulan', date('m Y'))->count(),
            'rhesusA1R' => Donor::where('umur', '>', 59)->where('rhesus', '+')->where('golongandarah', 'A')->where('bulan', date('m Y'))->count(),
            'rhesusA2R' => Donor::where('umur', '>', 59)->where('rhesus', '-')->where('golongandarah', 'A')->where('bulan', date('m Y'))->count(),
            'rhesusB1R' => Donor::where('umur', '>', 59)->where('rhesus', '+')->where('golongandarah', 'B')->where('bulan', date('m Y'))->count(),
            'rhesusB2R' => Donor::where('umur', '>', 59)->where('rhesus', '-')->where('golongandarah', 'B')->where('bulan', date('m Y'))->count(),
            'rhesusAB1R' => Donor::where('umur', '>', 59)->where('rhesus', '+')->where('golongandarah', 'AB')->where('bulan', date('m Y'))->count(),
            'rhesusAB2R' => Donor::where('umur', '>', 59)->where('rhesus', '-')->where('golongandarah', 'AB')->where('bulan', date('m Y'))->count(),



            $d = date('m'),
            // BULAN LALU
            // 18tahun
            'Ajumlahdonasi1' => Donor::where('umur', '<', 18)->where('bulan', 0 . $d - 1 . date(' Y'))->count(),
            'AsukarelabaruQ' => Donor::where('umur', '<', 18)->where('tempatdonor', 'PMI')->where('macamdonor', 'sukarela (baru)')->where('bulan', 0 . $d - 1 . date(' Y'))->count(),
            'AsukarelaulangQ' => Donor::where('umur', '<', 18)->where('tempatdonor', 'PMI')->where('macamdonor', 'sukarela (ulang)')->where('bulan', 0 . $d - 1 . date(' Y'))->count(),
            'ApenggantiQ' => Donor::where('umur', '<', 18)->where('tempatdonor', 'PMI')->where('macamdonor', 'pengganti')->where('bulan', 0 . $d - 1 . date(' Y'))->count(),
            'AbayaranQ' => Donor::where('umur', '<', 18)->where('tempatdonor', 'PMI')->where('macamdonor', 'bayaran')->where('bulan', 0 . $d - 1 . date(' Y'))->count(),
            'AmobileunitbaruQ' => Donor::where('umur', '<', 18)->where('tempatdonor', 'Mobile unit')->where('bulan', 0 . $d - 1 . date(' Y'))->count(),
            'AmobileunitulangQ' => Donor::where('umur', '<', 18)->where('tempatdonor', 'Mobile unit')->where('bulan', 0 . $d - 1 . date(' Y'))->count(),
            'Alaki2Q' => Donor::where('umur', '<', 18)->where('jeniskelamin', 'laki-laki')->where('bulan', 0 . $d - 1 . date(' Y'))->count(),
            'AperempuanQ' => Donor::where('umur', '<', 18)->where('jeniskelamin', 'perempuan')->where('bulan', 0 . $d - 1 . date(' Y'))->count(),
            'ArhesusO1Q' => Donor::where('umur', '<', 18)->where('rhesus', '+')->where('golongandarah', 'O')->where('bulan', 0 . $d - 1 . date(' Y'))->count(),
            'ArhesusO2Q' => Donor::where('umur', '<', 18)->where('rhesus', '-')->where('golongandarah', 'O')->where('bulan', 0 . $d - 1 . date(' Y'))->count(),
            'ArhesusA1Q' => Donor::where('umur', '<', 18)->where('rhesus', '+')->where('golongandarah', 'A')->where('bulan', 0 . $d - 1 . date(' Y'))->count(),
            'ArhesusA2Q' => Donor::where('umur', '<', 18)->where('rhesus', '-')->where('golongandarah', 'A')->where('bulan', 0 . $d - 1 . date(' Y'))->count(),
            'ArhesusB1Q' => Donor::where('umur', '<', 18)->where('rhesus', '+')->where('golongandarah', 'B')->where('bulan', 0 . $d - 1 . date(' Y'))->count(),
            'ArhesusB2Q' => Donor::where('umur', '<', 18)->where('rhesus', '-')->where('golongandarah', 'B')->where('bulan', 0 . $d - 1 . date(' Y'))->count(),
            'ArhesusAB1Q' => Donor::where('umur', '<', 18)->where('rhesus', '+')->where('golongandarah', 'AB')->where('bulan', 0 . $d - 1 . date(' Y'))->count(),
            'ArhesusAB2Q' => Donor::where('umur', '<', 18)->where('rhesus', '-')->where('golongandarah', 'AB')->where('bulan', 0 . $d - 1 . date(' Y'))->count(),
            // 18-24 tahun
            'Ajumlahdonasi2' => Donor::where('umur', '<', 25)->where('umur', '>', 17)->where('bulan', 0 . $d - 1 . date(' Y'))->count(),
            'Asukarelabaru' => Donor::where('umur', '<', 25)->where('tempatdonor', 'PMI')->where('umur', '>', 17)->where('macamdonor', 'sukarela (baru)')->where('bulan', 0 . $d - 1 . date(' Y'))->count(),
            'Asukarelaulang' => Donor::where('umur', '<', 25)->where('tempatdonor', 'PMI')->where('umur', '>', 17)->where('macamdonor', 'sukarela (ulang)')->where('bulan', 0 . $d - 1 . date(' Y'))->count(),
            'Apengganti' => Donor::where('umur', '<', 25)->where('tempatdonor', 'PMI')->where('umur', '>', 17)->where('macamdonor', 'pengganti')->where('bulan', 0 . $d - 1 . date(' Y'))->count(),
            'Abayaran' => Donor::where('umur', '<', 25)->where('tempatdonor', 'PMI')->where('umur', '>', 17)->where('macamdonor', 'bayaran')->where('bulan', 0 . $d - 1 . date(' Y'))->count(),
            'Amobileunitbaru' => Donor::where('umur', '<', 25)->where('umur', '>', 17)->where('tempatdonor', 'Mobile unit')->where('bulan', 0 . $d - 1 . date(' Y'))->count(),
            'Amobileunitulang' => Donor::where('umur', '<', 25)->where('umur', '>', 17)->where('tempatdonor', 'Mobile unit')->where('bulan', 0 . $d - 1 . date(' Y'))->count(),
            'Alaki2' => Donor::where('umur', '<', 25)->where('umur', '>', 17)->where('jeniskelamin', 'laki-laki')->where('bulan', 0 . $d - 1 . date(' Y'))->count(),
            'Aperempuan' => Donor::where('umur', '<', 25)->where('umur', '>', 17)->where('jeniskelamin', 'perempuan')->where('bulan', 0 . $d - 1 . date(' Y'))->count(),
            'ArhesusO1' => Donor::where('umur', '<', 25)->where('umur', '>', 17)->where('rhesus', '+')->where('golongandarah', 'O')->where('bulan', 0 . $d - 1 . date(' Y'))->count(),
            'ArhesusO2' => Donor::where('umur', '<', 25)->where('umur', '>', 17)->where('rhesus', '-')->where('golongandarah', 'O')->where('bulan', 0 . $d - 1 . date(' Y'))->count(),
            'ArhesusA1' => Donor::where('umur', '<', 25)->where('umur', '>', 17)->where('rhesus', '+')->where('golongandarah', 'A')->where('bulan', 0 . $d - 1 . date(' Y'))->count(),
            'ArhesusA2' => Donor::where('umur', '<', 25)->where('umur', '>', 17)->where('rhesus', '-')->where('golongandarah', 'A')->where('bulan', 0 . $d - 1 . date(' Y'))->count(),
            'ArhesusB1' => Donor::where('umur', '<', 25)->where('umur', '>', 17)->where('rhesus', '+')->where('golongandarah', 'B')->where('bulan', 0 . $d - 1 . date(' Y'))->count(),
            'ArhesusB2' => Donor::where('umur', '<', 25)->where('umur', '>', 17)->where('rhesus', '-')->where('golongandarah', 'B')->where('bulan', 0 . $d - 1 . date(' Y'))->count(),
            'ArhesusAB1' => Donor::where('umur', '<', 25)->where('umur', '>', 17)->where('rhesus', '+')->where('golongandarah', 'AB')->where('bulan', 0 . $d - 1 . date(' Y'))->count(),
            'ArhesusAB2' => Donor::where('umur', '<', 25)->where('umur', '>', 17)->where('rhesus', '-')->where('golongandarah', 'AB')->where('bulan', 0 . $d - 1 . date(' Y'))->count(),

            // 25 - 44
            'Ajumlahdonasi3' => Donor::where('umur', '<', 45)->where('umur', '>', 24)->where('bulan', 0 . $d - 1 . date(' Y'))->count(),
            'AsukarelabaruW' => Donor::where('umur', '<', 45)->where('tempatdonor', 'PMI')->where('umur', '>', 24)->where('macamdonor', 'sukarela (baru)')->where('bulan', 0 . $d - 1 . date(' Y'))->count(),
            'AsukarelaulangW' => Donor::where('umur', '<', 45)->where('tempatdonor', 'PMI')->where('umur', '>', 24)->where('macamdonor', 'sukarela (ulang)')->where('bulan', 0 . $d - 1 . date(' Y'))->count(),
            'ApenggantiW' => Donor::where('umur', '<', 45)->where('tempatdonor', 'PMI')->where('umur', '>', 24)->where('macamdonor', 'pengganti')->where('bulan', 0 . $d - 1 . date(' Y'))->count(),
            'AbayaranW' => Donor::where('umur', '<', 45)->where('tempatdonor', 'PMI')->where('umur', '>', 24)->where('macamdonor', 'bayaran')->where('bulan', 0 . $d - 1 . date(' Y'))->count(),
            'AmobileunitbaruW' => Donor::where('umur', '<', 45)->where('umur', '>', 24)->where('tempatdonor', 'Mobile unit')->where('bulan', 0 . $d - 1 . date(' Y'))->count(),
            'AmobileunitulangW' => Donor::where('umur', '<', 45)->where('umur', '>', 24)->where('tempatdonor', 'Mobile unit')->where('bulan', 0 . $d - 1 . date(' Y'))->count(),
            'Alaki2W' => Donor::where('umur', '<', 45)->where('umur', '>', 24)->where('jeniskelamin', 'laki-laki')->where('bulan', 0 . $d - 1 . date(' Y'))->count(),
            'AperempuanW' => Donor::where('umur', '<', 45)->where('umur', '>', 24)->where('jeniskelamin', 'perempuan')->where('bulan', 0 . $d - 1 . date(' Y'))->count(),
            'ArhesusO1W' => Donor::where('umur', '<', 45)->where('umur', '>', 24)->where('rhesus', '+')->where('golongandarah', 'O')->where('bulan', 0 . $d - 1 . date(' Y'))->count(),
            'ArhesusO2W' => Donor::where('umur', '<', 45)->where('umur', '>', 24)->where('rhesus', '-')->where('golongandarah', 'O')->where('bulan', 0 . $d - 1 . date(' Y'))->count(),
            'ArhesusA1W' => Donor::where('umur', '<', 45)->where('umur', '>', 24)->where('rhesus', '+')->where('golongandarah', 'A')->where('bulan', 0 . $d - 1 . date(' Y'))->count(),
            'ArhesusA2W' => Donor::where('umur', '<', 45)->where('umur', '>', 24)->where('rhesus', '-')->where('golongandarah', 'A')->where('bulan', 0 . $d - 1 . date(' Y'))->count(),
            'ArhesusB1W' => Donor::where('umur', '<', 45)->where('umur', '>', 24)->where('rhesus', '+')->where('golongandarah', 'B')->where('bulan', 0 . $d - 1 . date(' Y'))->count(),
            'ArhesusB2W' => Donor::where('umur', '<', 45)->where('umur', '>', 24)->where('rhesus', '-')->where('golongandarah', 'B')->where('bulan', 0 . $d - 1 . date(' Y'))->count(),
            'ArhesusAB1W' => Donor::where('umur', '<', 45)->where('umur', '>', 24)->where('rhesus', '+')->where('golongandarah', 'AB')->where('bulan', 0 . $d - 1 . date(' Y'))->count(),
            'ArhesusAB2W' => Donor::where('umur', '<', 45)->where('umur', '>', 24)->where('rhesus', '-')->where('golongandarah', 'AB')->where('bulan', 0 . $d - 1 . date(' Y'))->count(),

            // 45 tahun - 60 tahun
            'Ajumlahdonasi4' => Donor::where('umur', '<', 60)->where('umur', '>', 44)->where('bulan', 0 . $d - 1 . date(' Y'))->count(),
            'AsukarelabaruE' => Donor::where('umur', '<', 60)->where('tempatdonor', 'PMI')->where('umur', '>', 44)->where('macamdonor', 'sukarela (baru)')->where('bulan', 0 . $d - 1 . date(' Y'))->count(),
            'AsukarelaulangE' => Donor::where('umur', '<', 60)->where('tempatdonor', 'PMI')->where('umur', '>', 44)->where('macamdonor', 'sukarela (ulang)')->where('bulan', 0 . $d - 1 . date(' Y'))->count(),
            'ApenggantiE' => Donor::where('umur', '<', 60)->where('tempatdonor', 'PMI')->where('umur', '>', 44)->where('macamdonor', 'pengganti')->where('bulan', 0 . $d - 1 . date(' Y'))->count(),
            'AbayaranE' => Donor::where('umur', '<', 60)->where('tempatdonor', 'PMI')->where('umur', '>', 44)->where('macamdonor', 'bayaran')->where('bulan', 0 . $d - 1 . date(' Y'))->count(),
            'AmobileunitbaruE' => Donor::where('umur', '<', 60)->where('umur', '>', 44)->where('tempatdonor', 'Mobile unit')->where('bulan', 0 . $d - 1 . date(' Y'))->count(),
            'AmobileunitulangE' => Donor::where('umur', '<', 60)->where('umur', '>', 44)->where('tempatdonor', 'Mobile unit')->where('bulan', 0 . $d - 1 . date(' Y'))->count(),
            'Alaki2E' => Donor::where('umur', '<', 60)->where('umur', '>', 44)->where('jeniskelamin', 'laki-laki')->where('bulan', 0 . $d - 1 . date(' Y'))->count(),
            'AperempuanE' => Donor::where('umur', '<', 60)->where('umur', '>', 44)->where('jeniskelamin', 'perempuan')->where('bulan', 0 . $d - 1 . date(' Y'))->count(),
            'ArhesusO1E' => Donor::where('umur', '<', 60)->where('umur', '>', 44)->where('rhesus', '+')->where('golongandarah', 'O')->where('bulan', 0 . $d - 1 . date(' Y'))->count(),
            'ArhesusO2E' => Donor::where('umur', '<', 60)->where('umur', '>', 44)->where('rhesus', '-')->where('golongandarah', 'O')->where('bulan', 0 . $d - 1 . date(' Y'))->count(),
            'ArhesusA1E' => Donor::where('umur', '<', 60)->where('umur', '>', 44)->where('rhesus', '+')->where('golongandarah', 'A')->where('bulan', 0 . $d - 1 . date(' Y'))->count(),
            'ArhesusA2E' => Donor::where('umur', '<', 60)->where('umur', '>', 44)->where('rhesus', '-')->where('golongandarah', 'A')->where('bulan', 0 . $d - 1 . date(' Y'))->count(),
            'ArhesusB1E' => Donor::where('umur', '<', 60)->where('umur', '>', 44)->where('rhesus', '+')->where('golongandarah', 'B')->where('bulan', 0 . $d - 1 . date(' Y'))->count(),
            'ArhesusB2E' => Donor::where('umur', '<', 60)->where('umur', '>', 44)->where('rhesus', '-')->where('golongandarah', 'B')->where('bulan', 0 . $d - 1 . date(' Y'))->count(),
            'ArhesusAB1E' => Donor::where('umur', '<', 60)->where('umur', '>', 44)->where('rhesus', '+')->where('golongandarah', 'AB')->where('bulan', 0 . $d - 1 . date(' Y'))->count(),
            'ArhesusAB2E' => Donor::where('umur', '<', 60)->where('umur', '>', 44)->where('rhesus', '-')->where('golongandarah', 'AB')->where('bulan', 0 . $d - 1 . date(' Y'))->count(),
            // 60 tahun keatas

            'Ajumlahdonasi5' => Donor::where('umur', '>', 59)->where('bulan', 0 . $d - 1 . date(' Y'))->count(),
            'AsukarelabaruR' => Donor::where('umur', '>', 59)->where('tempatdonor', 'PMI')->where('macamdonor', 'sukarela (baru)')->where('bulan', 0 . $d - 1 . date(' Y'))->count(),
            'AsukarelaulangR' => Donor::where('umur', '>', 59)->where('tempatdonor', 'PMI')->where('macamdonor', 'sukarela (ulang)')->where('bulan', 0 . $d - 1 . date(' Y'))->count(),
            'ApenggantiR' => Donor::where('umur', '>', 59)->where('tempatdonor', 'PMI')->where('macamdonor', 'pengganti')->where('bulan', 0 . $d - 1 . date(' Y'))->count(),
            'AbayaranR' => Donor::where('umur', '>', 59)->where('tempatdonor', 'PMI')->where('macamdonor', 'bayaran')->where('bulan', 0 . $d - 1 . date(' Y'))->count(),
            'AmobileunitbaruR' => Donor::where('umur', '>', 59)->where('tempatdonor', 'Mobile unit')->where('bulan', 0 . $d - 1 . date(' Y'))->count(),
            'AmobileunitulangR' => Donor::where('umur', '>', 59)->where('tempatdonor', 'Mobile unit')->where('bulan', 0 . $d - 1 . date(' Y'))->count(),
            'Alaki2R' => Donor::where('umur', '>', 59)->where('jeniskelamin', 'laki-laki')->where('bulan', 0 . $d - 1 . date(' Y'))->count(),
            'AperempuanR' => Donor::where('umur', '>', 59)->where('jeniskelamin', 'perempuan')->where('bulan', 0 . $d - 1 . date(' Y'))->count(),
            'ArhesusO1R' => Donor::where('umur', '>', 59)->where('rhesus', '+')->where('golongandarah', 'O')->where('bulan', 0 . $d - 1 . date(' Y'))->count(),
            'ArhesusO2R' => Donor::where('umur', '>', 59)->where('rhesus', '-')->where('golongandarah', 'O')->where('bulan', 0 . $d - 1 . date(' Y'))->count(),
            'ArhesusA1R' => Donor::where('umur', '>', 59)->where('rhesus', '+')->where('golongandarah', 'A')->where('bulan', 0 . $d - 1 . date(' Y'))->count(),
            'ArhesusA2R' => Donor::where('umur', '>', 59)->where('rhesus', '-')->where('golongandarah', 'A')->where('bulan', 0 . $d - 1 . date(' Y'))->count(),
            'ArhesusB1R' => Donor::where('umur', '>', 59)->where('rhesus', '+')->where('golongandarah', 'B')->where('bulan', 0 . $d - 1 . date(' Y'))->count(),
            'ArhesusB2R' => Donor::where('umur', '>', 59)->where('rhesus', '-')->where('golongandarah', 'B')->where('bulan', 0 . $d - 1 . date(' Y'))->count(),
            'ArhesusAB1R' => Donor::where('umur', '>', 59)->where('rhesus', '+')->where('golongandarah', 'AB')->where('bulan', 0 . $d - 1 . date(' Y'))->count(),
            'ArhesusAB2R' => Donor::where('umur', '>', 59)->where('rhesus', '-')->where('golongandarah', 'AB')->where('bulan', 0 . $d - 1 . date(' Y'))->count(),
        ]);
    }
}
